---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/

instanceName: admin

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey
