x-prereq-dirs:
  - ./appdata/lidarr
x-managed-files:
  - path: ./appdata/lidarr/scripts/beets-post-import.sh
    mode: "0755"

services:
  lidarr:
    image: lscr.io/linuxserver/lidarr:3.1.0
    container_name: lidarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./appdata/lidarr:/config
      - /data:/data
    ports:
      - 8686:8686
    labels:
      traefik.enable: true
      traefik.http.routers.lidarr.middlewares: protected-edge-auth@file
      homepage.instance.admin.group: Arr
      homepage.instance.admin.name: Lidarr
      homepage.instance.admin.href: https://${HOMEPAGE_FQDN}
      homepage.instance.admin.description: Music management
      homepage.instance.admin.icon: lidarr
    networks:
      - shared

networks:
  shared:
    name: shared
    external: true
