services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    hostname: sonarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./appdata/sonarr:/config
      - /data:/data
    ports:
      - 8989:8989
    labels:
      traefik.enable: true
      homepage.instance.admin.group: Media
      homepage.instance.admin.name: Sonarr
      homepage.instance.admin.href: https://${HOMEPAGE_FQDN}
      homepage.instance.admin.description: TV series management
      homepage.instance.admin.icon: sonarr
    networks:
      - servarr-internal

networks:
  servarr-internal:
    name: servarr-internal
    external: true