services:
  sabnzbd:
    container_name: sabnzbd
    labels:
      homepage.group: Downloads
      homepage.name: SABnzbd
      homepage.href: https://${HOMEPAGE_FQDN}
      homepage.description: Usenet client
      homepage.icon: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Montreal
    image: lscr.io/linuxserver/sabnzbd:latest
    restart: unless-stopped
    ports:
      - $SABNZBD_PORT:8080 # sabnzbd
    volumes:
      - ./appdata/sabnzbd:/config
      - /data:/data #optional
      - /ephemeral/sabnzbd:/ephemeral #optional
networks: {}
