networks:
  shared:
    name: shared
    external: true

services:
  homepage-media:
    image: ghcr.io/gethomepage/homepage:v1.12.3
    container_name: homepage-media
    restart: unless-stopped
    ports:
      - 3001:3000
    volumes:
      - ./appdata/homepage/config:/app/config
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - HOMEPAGE_INSTANCE_NAME=media
      - HOMEPAGE_ALLOWED_HOSTS=localhost:3001,127.0.0.1:3001,[::1]:3001,portal.faviann.vms:3001,homepage.media.faviann.com
    networks:
      - shared
    labels:
      traefik.enable: true
      traefik.http.routers.homepage-media.rule: Host(`homepage.media.faviann.com`)
      traefik.http.routers.homepage-media.middlewares: protected-edge-auth@file
