---
services:
  portal-entry:
    image: nginx:alpine
    container_name: portal-entry
    restart: unless-stopped
    volumes:
      - ./appdata/nginx/conf.d:/etc/nginx/conf.d:ro
    networks:
      - shared
    labels:
      traefik.enable: true
      traefik.http.routers.portal-entry.rule: Host(`faviann.com`)
      traefik.http.routers.portal-entry.middlewares: protected-edge-auth@file
networks:
  shared:
    external: true
