---
# Default variables for proxmox_api_adapter role

# Proxmox API endpoint defaults
proxmox_api_adapter_host: "{{ proxmox_api_host }}"
proxmox_api_adapter_delegate_host: "{{ proxmox_delegate_host }}"
proxmox_api_adapter_port: "{{ proxmox_api_port | default(8006) }}"
proxmox_api_adapter_user: "{{ proxmox_api_user }}"
proxmox_api_adapter_token_id: "{{ proxmox_api_token_id }}"
proxmox_api_adapter_token_secret: "{{ proxmox_api_token_secret }}"
proxmox_api_adapter_verify_ssl: "{{ proxmox_verify_ssl | default(true) }}"

# Default node
proxmox_api_adapter_node: "{{ proxmox_default_node }}"
