x-prereq-dirs:
  - ./appdata/jellyfin/config
  - /ephemeral/jellyfin/cache
  - /ephemeral/jellyfin/metadata

services:
  jellyfin:
    container_name: jellyfin
    image: jellyfin/jellyfin:10.11.8
    restart: unless-stopped
    user: ${PUID}:${PGID}
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - JELLYFIN_PublishedServerUrl=https://${HOMEPAGE_FQDN}
    volumes:
      - /ephemeral/jellyfin/cache:/cache
      - ./appdata/jellyfin/config:/config
      - /ephemeral/jellyfin/metadata:/config/metadata
      - /data/media:/data/media
    ports:
      - 8096:8096
    labels:
      - traefik.enable=true
      - homepage.group=Media
      - homepage.name=${COMPOSE_PROJECT_NAME}
      - homepage.icon=jellyfin
      - homepage.href=https://${HOMEPAGE_FQDN}
      - homepage.description=Media server
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
