---
x-prereq-dirs:
  - /data/overmind/postgres/pgdata

services:
  postgres:
    image: docker.io/library/postgres:18
    container_name: overmind-postgres
    restart: unless-stopped
    stop_grace_period: 60s
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB:?database name required}
      POSTGRES_USER: ${POSTGRES_USER:?database user required}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?database password required}
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -d "$${POSTGRES_DB}" -U "$${POSTGRES_USER}"
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 20s
    volumes:
      - /data/overmind/postgres/pgdata:/var/lib/postgresql
