services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    hostname: radarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./appdata/radarr:/config
      - /data:/data
    ports:
      - 7878:7878
    labels:
      traefik.enable: true
      homepage.instance.admin.group: Media
      homepage.instance.admin.name: Radarr
      homepage.instance.admin.href: https://${HOMEPAGE_FQDN}
      homepage.instance.admin.description: Movie management
      homepage.instance.admin.icon: radarr
    networks:
      - servarr-internal

networks:
  servarr-internal:
    name: servarr-internal
    external: true