x-prereq-dirs:
  - ./appdata/mylar

services:
  mylar:
    image: lscr.io/linuxserver/mylar:latest
    container_name: mylar
    hostname: mylar
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./appdata/mylar:/config
      - /data:/data
    ports:
      - 8090:8090
    labels:
      traefik.enable: true
      diun.enable: "true"
      homepage.instance.admin.group: Media
      homepage.instance.admin.name: Mylar
      homepage.instance.admin.href: https://${HOMEPAGE_FQDN}
      homepage.instance.admin.description: Comic management
      homepage.instance.admin.icon: mylar
    networks:
      - servarr-internal

networks:
  servarr-internal:
    name: servarr-internal
    external: true