x-prereq-dirs:
  - ./appdata/config
  - ./appdata/pgdata
  - ./appdata/redis
  - /ephemeral/readmeabook/cache
  - /data/downloads/readmeabook

services:
  readmeabook:
    image: ghcr.io/kikootwo/readmeabook:1.1.8
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      UMASK: ${UMASK}
      LOG_LEVEL: ${LOG_LEVEL}
      PUBLIC_URL: https://${HOMEPAGE_FQDN}
      JWT_SECRET: ${JWT_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      CONFIG_ENCRYPTION_KEY: ${CONFIG_ENCRYPTION_KEY}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DISABLE_LOCAL_LOGIN: ${DISABLE_LOCAL_LOGIN}
    volumes:
      - ./appdata/config:/app/config
      - /ephemeral/readmeabook/cache:/app/cache
      - /data/downloads/readmeabook:/downloads
      - /data/media/audiobooks:/media
      - /data:/data
      - ./appdata/pgdata:/var/lib/postgresql/data
      - ./appdata/redis:/var/lib/redis
    labels:
      traefik.enable: true
      homepage.group: Media
      homepage.name: ReadMeABook
      homepage.href: https://${HOMEPAGE_FQDN}
      homepage.description: Audiobook request and automation engine
      homepage.icon: mdi-book-music
