x-prereq-dirs:
  - ./appdata/bazarr

services:
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    hostname: bazarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./appdata/bazarr:/config
      - /data:/data
    ports:
      - 6767:6767
    labels:
      traefik.enable: true
      homepage.instance.admin.group: Media
      homepage.instance.admin.name: Bazarr
      homepage.instance.admin.href: https://${HOMEPAGE_FQDN}
      homepage.instance.admin.description: Subtitle management
      homepage.instance.admin.icon: bazarr
    networks:
      - servarr-internal

networks:
  servarr-internal:
    name: servarr-internal
    external: true