x-prereq-dirs:
  - ./appdata/prowlarr

services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:2.3.5
    container_name: prowlarr
    restart: unless-stopped
    depends_on:
      - flaresolverr-custom
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./appdata/prowlarr:/config
      - /data:/data
    ports:
      - 9696:9696
    labels:
      traefik.enable: true
      traefik.http.routers.prowlarr.middlewares: protected-edge-auth@file
      homepage.instance.admin.group: Arr
      homepage.instance.admin.name: Prowlarr
      homepage.instance.admin.href: https://${HOMEPAGE_FQDN}
      homepage.instance.admin.description: Indexer management
      homepage.instance.admin.icon: prowlarr
    networks:
      - servarr-internal

  flaresolverr-custom:
    image: 21hsmw/flaresolverr:nodriver
    container_name: flaresolverr-custom
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DRIVER=nodriver
    networks:
      - servarr-internal

networks:
  servarr-internal:
    name: servarr-internal
    external: true
