---
x-prereq-dirs:
  - ./appdata/prowlarr

services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:2.6.5@sha256:f9151e5bc1025c6d0a630d503210cdcb6bb55a7cc098562609d96a408d838902
    container_name: prowlarr
    restart: unless-stopped
    depends_on:
      - flaresolverr-custom
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./appdata/prowlarr:/config
      - /data:/data
    ports:
      - 9696:9696
    labels:
      traefik.enable: true
      traefik.http.routers.prowlarr.middlewares: protected-edge-auth@file
      homepage.instance.admin.group: Arr
      homepage.instance.admin.name: Prowlarr
      homepage.instance.admin.href: https://${HOMEPAGE_FQDN}
      homepage.instance.admin.description: Indexer management
      homepage.instance.admin.icon: prowlarr
    networks:
      - shared

  flaresolverr-custom:
    image: 21hsmw/flaresolverr:nodriver@sha256:dca8cda5852b04e6142752fc044c9845eb536353ea6f8b7bb58b4ff9419538fa
    container_name: flaresolverr-custom
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DRIVER=nodriver
    ports:
      - "8191:8191"
    networks:
      - shared

networks:
  shared:
    name: shared
    external: true
