x-prereq-dirs:
  - ./appdata/database
  - ./appdata/authentik/data
  - ./appdata/authentik/certs
  - ./appdata/authentik/custom-templates

services:
  postgresql:
    volumes:
      - ./appdata/database:/var/lib/postgresql/data
    networks:
      - idm
  server:
    volumes:
      - ./appdata/authentik/data:/data
      - ./appdata/authentik/custom-templates:/templates
      - ./appdata/authentik/blueprints:/blueprints/custom
    networks:
      - proxy
      - idm
    environment:
      - AUTHENTIK_PROXY_HEADERS=true
      - AUTHENTIK_COOKIE_DOMAIN=.faviann.com
    labels:
      - traefik.enable=true
      - diun.enable=true
      - traefik.docker.network=proxy
  worker:
    environment:
      AUTHENTIK_EMAIL__FROM: ${AUTHENTIK_EMAIL__FROM}
      AUTHENTIK_COOKIE_DOMAIN: .faviann.com
    volumes:
      - ./appdata/authentik/data:/data
      - ./appdata/authentik/certs:/certs
      - ./appdata/authentik/custom-templates:/templates
      - ./appdata/authentik/blueprints:/blueprints/custom
    networks:
      - idm
networks:
  idm:
    name: idm
    driver: bridge
  proxy:
    external: true
