services:
  postgresql:
    volumes:
      - ./appdata/database:/var/lib/postgresql/data
    networks:
      - idm
  server:
    volumes:
      - ./appdata/authentik/data:/data
      - ./appdata/authentik/custom-templates:/templates
    networks:
      - proxy
      - idm
    environment:
      - AUTHENTIK_PROXY_HEADERS=true
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
  worker:
    environment:
      AUTHENTIK_EMAIL__FROM: ${AUTHENTIK_EMAIL__FROM}
    volumes:
      - ./appdata/authentik/data:/data
      - ./appdata/authentik/certs:/certs
      - ./appdata/authentik/custom-templates:/templates
    networks:
      - idm
networks:
  idm:
    name: idm
    driver: bridge
  proxy:
    external: true
