x-prereq-dirs:
  - ./appdata/notifiarr

services:
  notifiarr:
    image: golift/notifiarr
    container_name: notifiarr
    hostname: notifiarr-servarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./appdata/notifiarr:/config
      - /data:/data
    ports:
      - 5454:5454
    labels:
      traefik.enable: true
      traefik.http.routers.notifiarr.middlewares: protected-edge-auth@file
      homepage.instance.admin.group: Operations
      homepage.instance.admin.name: Notifiarr
      homepage.instance.admin.href: https://${HOMEPAGE_FQDN}
      homepage.instance.admin.description: Notification and automation companion
      homepage.instance.admin.icon: notifiarr
    networks:
      - servarr-internal

networks:
  servarr-internal:
    name: servarr-internal
    external: true
