map $http_x_authentik_groups $redirect_target {
    ~*admin    https://homepage.admin.faviann.com;
    ~*home     https://homepage.home.faviann.com;
    default    https://homepage.media.faviann.com;
}

server {
    listen 80;
    server_name _;
    return 302 $redirect_target;
}
