map $http_x_authentik_groups $redirect_target {
    ~*admin    https://admin.faviann.com;
    ~*editors  https://home.faviann.com;
    default    https://media.faviann.com;
}

server {
    listen 80;
    server_name _;
    return 302 $redirect_target;
}
