x-prereq-dirs:
  - ./appdata/mealie

services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v3.14.0
    container_name: mealie
    restart: unless-stopped
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 1024M
    volumes:
      - ./appdata/mealie:/app/data
    environment:
      - ALLOW_SIGNUP=false
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - BASE_URL=${BASE_URL}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_USER=${SMTP_USER}
      - SMTP_FROM_EMAIL=${SMTP_FROM_EMAIL}
      - DEFAULT_EMAIL=${DEFAULT_EMAIL}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - MAX_WORKERS=${MAX_WORKERS}
    labels:
      - traefik.enable=true
      - diun.enable=true
      - homepage.group=Home
      - homepage.name=${COMPOSE_PROJECT_NAME}
      - homepage.icon=mealie
      - homepage.href=https://${HOMEPAGE_FQDN}
      - homepage.description=Recipe manager
