networks:
  proxy:
    name: proxy
    external: true
    
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 3000:3000
    volumes:
      - ./appdata/homepage/config:/app/config # Make sure your local config directory exists
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - HOMEPAGE_ALLOWED_HOSTS=localhost:3000,127.0.0.1:3000,[::1]:3000,portal.faviann.vms:3000,homepage.faviann.com
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.domain=faviann.com
      - traefik.http.routers.frontpage.rule=Host(`homepage.faviann.com`)
      - traefik.http.routers.frontpage.entrypoints=websecure
      - traefik.http.routers.frontpage.tls=true
      - traefik.http.services.frontpage.loadbalancer.server.port=3000